import { cfgToPDA } from "@/features/pda/cfg-to-pda-agent";
import { tool } from "ai";
import { z } from "zod";
import { createPDAExecution, simulatePDA, stepPDA, type PDA, validatePDA } from "@/features/pda/model-agent";
export type PDAState = { selectedId: string | null; pdas: Record<string, PDA>; executions: Record<string, ReturnType<typeof createPDAExecution>> };
export const createInitialPDAState = (): PDAState => ({ selectedId: null, pdas: {}, executions: {} });
type Context = { get state(): PDAState; commit(next: PDAState): void };
const symbol = z.string().min(1);
const transition = z.object({ id: symbol.optional(), from: symbol, to: symbol, inputSymbol: symbol, stackTop: symbol, operation: z.enum(["push", "pop", "replace", "noop"]), pushSymbols: z.array(symbol).optional() });
const get = (ctx: Context, requested?: string) => { const id = requested ?? ctx.state.selectedId; return id ? ctx.state.pdas[id] : undefined; };
const commit = (ctx: Context, state: PDAState) => { ctx.commit(structuredClone(state)); return { ok: true, success: true, summary: "PDA updated." }; };
export function createPDATools(ctx: Context) { return {
  create_pda: tool({ description: "Create a pushdown automaton.", inputSchema: z.object({ pdaId: symbol, states: z.array(z.object({ id: symbol, label: z.string().optional(), accepting: z.boolean().optional() })).min(1), inputAlphabet: z.array(symbol), stackAlphabet: z.array(symbol), startState: symbol, acceptStates: z.array(symbol).default([]), initialStackSymbol: z.string().optional(), acceptanceMode: z.enum(["final_state", "empty_stack", "both"]).default("final_state"), transitions: z.array(transition).default([]), input: z.string().default("") }), execute: async (input) => { if (ctx.state.pdas[input.pdaId]) return { ok: false, success: false, summary: "PDA ID already exists." }; const pda: PDA = { id: input.pdaId, states: input.states.map((state) => ({ ...state, label: state.label ?? state.id })), inputAlphabet: input.inputAlphabet, stackAlphabet: input.stackAlphabet, startState: input.startState, acceptStates: input.acceptStates, initialStackSymbol: input.initialStackSymbol, acceptanceMode: input.acceptanceMode, transitions: input.transitions.map((item, index) => ({ ...item, id: item.id ?? `t${index}` })) }; const validation = validatePDA(pda); if (!validation.valid) return { ok: false, success: false, summary: validation.issues[0] }; return commit(ctx, { selectedId: pda.id, pdas: { ...ctx.state.pdas, [pda.id]: pda }, executions: { ...ctx.state.executions, [pda.id]: createPDAExecution(pda, input.input) } }); } }),
  inspect_pda: tool({ description: "Inspect a PDA definition.", inputSchema: z.object({ pdaId: symbol.optional() }), execute: async ({ pdaId }) => { const pda = get(ctx, pdaId); return pda ? { ok: true, success: true, summary: "PDA inspected.", data: pda } : { ok: false, success: false, summary: "PDA not found." }; } }),
  validate_pda: tool({ description: "Validate a PDA.", inputSchema: z.object({ pdaId: symbol.optional() }), execute: async ({ pdaId }) => { const pda = get(ctx, pdaId); const validation = pda && validatePDA(pda); return validation ? { ok: validation.valid, success: validation.valid, summary: validation.valid ? "PDA is valid." : validation.issues.join(" "), data: validation } : { ok: false, success: false, summary: "PDA not found." }; } }),
  simulate_pda: tool({ description: "Simulate all PDA branches to completion.", inputSchema: z.object({ pdaId: symbol.optional(), input: z.string().optional() }), execute: async ({ pdaId, input }) => { const pda = get(ctx, pdaId); if (!pda) return { ok: false, success: false, summary: "PDA not found." }; const execution = simulatePDA(pda, input ?? ctx.state.executions[pda.id]?.input ?? ""); ctx.commit({ ...ctx.state, executions: { ...ctx.state.executions, [pda.id]: execution } }); return { ok: execution.result !== "rejected", success: execution.result !== "rejected", summary: `Simulation ${execution.result}.`, data: execution }; } }),
  step_pda: tool({ description: "Advance every live PDA configuration one transition.", inputSchema: z.object({ pdaId: symbol.optional() }), execute: async ({ pdaId }) => { const pda = get(ctx, pdaId); if (!pda) return { ok: false, success: false, summary: "PDA not found." }; const execution = stepPDA(pda, ctx.state.executions[pda.id] ?? createPDAExecution(pda)); ctx.commit({ ...ctx.state, executions: { ...ctx.state.executions, [pda.id]: execution } }); return { ok: true, success: true, summary: `Advanced to ${execution.configurations.length} configuration(s).`, data: execution }; } }),
  reset_pda: tool({ description: "Reset PDA execution.", inputSchema: z.object({ pdaId: symbol.optional(), input: z.string().optional() }), execute: async ({ pdaId, input }) => { const pda = get(ctx, pdaId); if (!pda) return { ok: false, success: false, summary: "PDA not found." }; return commit(ctx, { ...ctx.state, executions: { ...ctx.state.executions, [pda.id]: createPDAExecution(pda, input ?? ctx.state.executions[pda.id]?.input ?? "") } }); } }),
  get_pda_configuration: tool({ description: "Read all live PDA configurations.", inputSchema: z.object({ pdaId: symbol.optional() }), execute: async ({ pdaId }) => { const pda = get(ctx, pdaId); return pda ? { ok: true, success: true, summary: "Configuration read.", data: ctx.state.executions[pda.id] } : { ok: false, success: false, summary: "PDA not found." }; } }),
  modify_pda: tool({ description: "Replace PDA input alphabet or stack alphabet.", inputSchema: z.object({ pdaId: symbol.optional(), inputAlphabet: z.array(symbol).optional(), stackAlphabet: z.array(symbol).optional() }), execute: async ({ pdaId, ...change }) => { const pda = get(ctx, pdaId); if (!pda) return { ok: false, success: false, summary: "PDA not found." }; const next = { ...pda, ...change }; return commit(ctx, { ...ctx.state, pdas: { ...ctx.state.pdas, [pda.id]: next }, executions: { ...ctx.state.executions, [pda.id]: createPDAExecution(next, ctx.state.executions[pda.id]?.input) } }); } }),
  add_pda_state: tool({ description: "Add a PDA state.", inputSchema: z.object({ pdaId: symbol.optional(), stateId: symbol, accepting: z.boolean().optional() }), execute: async ({ pdaId, stateId, accepting }) => { const pda = get(ctx, pdaId); if (!pda) return { ok: false, success: false, summary: "PDA not found." }; return commit(ctx, { ...ctx.state, pdas: { ...ctx.state.pdas, [pda.id]: { ...pda, states: [...pda.states, { id: stateId, label: stateId, accepting }], acceptStates: accepting ? [...pda.acceptStates, stateId] : pda.acceptStates } }, executions: ctx.state.executions }); } }),
  add_pda_transition: tool({ description: "Add a PDA transition.", inputSchema: z.object({ pdaId: symbol.optional(), transition }), execute: async ({ pdaId, transition: item }) => { const pda = get(ctx, pdaId); if (!pda) return { ok: false, success: false, summary: "PDA not found." }; const transition = { ...item, id: item.id ?? `t${pda.transitions.length}` }; return commit(ctx, { ...ctx.state, pdas: { ...ctx.state.pdas, [pda.id]: { ...pda, transitions: [...pda.transitions, transition] } }, executions: ctx.state.executions }); } }),
  remove_pda_transition: tool({ description: "Remove a PDA transition.", inputSchema: z.object({ pdaId: symbol.optional(), transitionId: symbol }), execute: async ({ pdaId, transitionId }) => { const pda = get(ctx, pdaId); if (!pda) return { ok: false, success: false, summary: "PDA not found." }; return commit(ctx, { ...ctx.state, pdas: { ...ctx.state.pdas, [pda.id]: { ...pda, transitions: pda.transitions.filter((item) => item.id !== transitionId) } }, executions: ctx.state.executions }); } }),
  set_acceptance_mode: tool({ description: "Set final-state, empty-stack, or both acceptance.", inputSchema: z.object({ pdaId: symbol.optional(), acceptanceMode: z.enum(["final_state", "empty_stack", "both"]) }), execute: async ({ pdaId, acceptanceMode }) => { const pda = get(ctx, pdaId); return pda ? commit(ctx, { ...ctx.state, pdas: { ...ctx.state.pdas, [pda.id]: { ...pda, acceptanceMode } }, executions: ctx.state.executions }) : { ok: false, success: false, summary: "PDA not found." }; } }),
  convert_cfg_to_pda: tool({ description: "Convert a CFG to an equivalent empty-stack PDA.", inputSchema: z.object({ grammar: z.any(), pdaId: symbol.optional() }), execute: async ({ grammar, pdaId }) => { const steps = cfgToPDA(grammar, pdaId); const pda = steps.at(-1)!.pda; return commit(ctx, { selectedId: pda.id, pdas: { ...ctx.state.pdas, [pda.id]: pda }, executions: { ...ctx.state.executions, [pda.id]: createPDAExecution(pda) } }); } }),
  step_cfg_to_pda_conversion: tool({ description: "Return one CFG-to-PDA construction step.", inputSchema: z.object({ grammar: z.any(), step: z.number().int().nonnegative(), pdaId: symbol.optional() }), execute: async ({ grammar, step, pdaId }) => { const steps = cfgToPDA(grammar, pdaId); const item = steps[Math.min(step, steps.length - 1)]; return { ok: true, success: true, summary: item.label, data: item }; } }),
  reset_cfg_to_pda_conversion: tool({ description: "Reset CFG-to-PDA conversion to its initial stack setup.", inputSchema: z.object({ grammar: z.any(), pdaId: symbol.optional() }), execute: async ({ grammar, pdaId }) => { const item = cfgToPDA(grammar, pdaId)[0]; return { ok: true, success: true, summary: item.label, data: item }; } }),
}; }
